// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public interface DaoGpsServicePrx extends Ice.ObjectPrx
{
    public boolean getBsRecords(BsGetRequest req, BsGetResponseHolder res);

    public boolean getBsRecords(BsGetRequest req, BsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBsRecords(BsGetRequest req);

    public Ice.AsyncResult begin_getBsRecords(BsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBsRecords(BsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBsRecords(BsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBsRecords(BsGetRequest req, Callback_DaoGpsService_getBsRecords __cb);

    public Ice.AsyncResult begin_getBsRecords(BsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getBsRecords __cb);

    public boolean end_getBsRecords(BsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getLatestBsRecord(LatestBsGetRequest req, LatestBsGetResponseHolder res);

    public boolean getLatestBsRecord(LatestBsGetRequest req, LatestBsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestBsRecord(LatestBsGetRequest req);

    public Ice.AsyncResult begin_getLatestBsRecord(LatestBsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestBsRecord(LatestBsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestBsRecord(LatestBsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestBsRecord(LatestBsGetRequest req, Callback_DaoGpsService_getLatestBsRecord __cb);

    public Ice.AsyncResult begin_getLatestBsRecord(LatestBsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getLatestBsRecord __cb);

    public boolean end_getLatestBsRecord(LatestBsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getRecentBsRecords(RecentBsGetRequest req, RecentBsGetResponseHolder res);

    public boolean getRecentBsRecords(RecentBsGetRequest req, RecentBsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getRecentBsRecords(RecentBsGetRequest req);

    public Ice.AsyncResult begin_getRecentBsRecords(RecentBsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getRecentBsRecords(RecentBsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getRecentBsRecords(RecentBsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getRecentBsRecords(RecentBsGetRequest req, Callback_DaoGpsService_getRecentBsRecords __cb);

    public Ice.AsyncResult begin_getRecentBsRecords(RecentBsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getRecentBsRecords __cb);

    public boolean end_getRecentBsRecords(RecentBsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getFirstBsRecord(BsGetRequest req, BsGetResponseHolder res);

    public boolean getFirstBsRecord(BsGetRequest req, BsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFirstBsRecord(BsGetRequest req);

    public Ice.AsyncResult begin_getFirstBsRecord(BsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFirstBsRecord(BsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFirstBsRecord(BsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFirstBsRecord(BsGetRequest req, Callback_DaoGpsService_getFirstBsRecord __cb);

    public Ice.AsyncResult begin_getFirstBsRecord(BsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getFirstBsRecord __cb);

    public boolean end_getFirstBsRecord(BsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getFirstGpsRecord(GpsGetRequest req, GpsGetResponseHolder res);

    public boolean getFirstGpsRecord(GpsGetRequest req, GpsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFirstGpsRecord(GpsGetRequest req);

    public Ice.AsyncResult begin_getFirstGpsRecord(GpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFirstGpsRecord(GpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFirstGpsRecord(GpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFirstGpsRecord(GpsGetRequest req, Callback_DaoGpsService_getFirstGpsRecord __cb);

    public Ice.AsyncResult begin_getFirstGpsRecord(GpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getFirstGpsRecord __cb);

    public boolean end_getFirstGpsRecord(GpsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getLatestGpsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res);

    public boolean getLatestGpsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestGpsRecord(LatestGpsGetRequest req);

    public Ice.AsyncResult begin_getLatestGpsRecord(LatestGpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestGpsRecord(LatestGpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestGpsRecord(LatestGpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestGpsRecord(LatestGpsGetRequest req, Callback_DaoGpsService_getLatestGpsRecord __cb);

    public Ice.AsyncResult begin_getLatestGpsRecord(LatestGpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getLatestGpsRecord __cb);

    public boolean end_getLatestGpsRecord(LatestGpsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getRecentGpsRecords(RecentGpsGetRequest req, RecentGpsGetResponseHolder res);

    public boolean getRecentGpsRecords(RecentGpsGetRequest req, RecentGpsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getRecentGpsRecords(RecentGpsGetRequest req);

    public Ice.AsyncResult begin_getRecentGpsRecords(RecentGpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getRecentGpsRecords(RecentGpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getRecentGpsRecords(RecentGpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getRecentGpsRecords(RecentGpsGetRequest req, Callback_DaoGpsService_getRecentGpsRecords __cb);

    public Ice.AsyncResult begin_getRecentGpsRecords(RecentGpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getRecentGpsRecords __cb);

    public boolean end_getRecentGpsRecords(RecentGpsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getGpsRecords(GpsGetRequest req, GpsGetResponseHolder res);

    public boolean getGpsRecords(GpsGetRequest req, GpsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsRecords(GpsGetRequest req);

    public Ice.AsyncResult begin_getGpsRecords(GpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsRecords(GpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsRecords(GpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsRecords(GpsGetRequest req, Callback_DaoGpsService_getGpsRecords __cb);

    public Ice.AsyncResult begin_getGpsRecords(GpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getGpsRecords __cb);

    public boolean end_getGpsRecords(GpsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getGpsRecordsEx(GpsGetRequest req, GpsGetExResponseHolder res);

    public boolean getGpsRecordsEx(GpsGetRequest req, GpsGetExResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsRecordsEx(GpsGetRequest req);

    public Ice.AsyncResult begin_getGpsRecordsEx(GpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsRecordsEx(GpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsRecordsEx(GpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsRecordsEx(GpsGetRequest req, Callback_DaoGpsService_getGpsRecordsEx __cb);

    public Ice.AsyncResult begin_getGpsRecordsEx(GpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getGpsRecordsEx __cb);

    public boolean end_getGpsRecordsEx(GpsGetExResponseHolder res, Ice.AsyncResult __result);

    public boolean getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, LatestGpsGetResponseHolder res);

    public boolean getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, LatestGpsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req);

    public Ice.AsyncResult begin_getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, Callback_DaoGpsService_getLatestGpsRecordByImei __cb);

    public Ice.AsyncResult begin_getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getLatestGpsRecordByImei __cb);

    public boolean end_getLatestGpsRecordByImei(LatestGpsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getGpsRecordsByImei(GpsGetRequest req, GpsGetExResponseHolder res);

    public boolean getGpsRecordsByImei(GpsGetRequest req, GpsGetExResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsRecordsByImei(GpsGetRequest req);

    public Ice.AsyncResult begin_getGpsRecordsByImei(GpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsRecordsByImei(GpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsRecordsByImei(GpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsRecordsByImei(GpsGetRequest req, Callback_DaoGpsService_getGpsRecordsByImei __cb);

    public Ice.AsyncResult begin_getGpsRecordsByImei(GpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getGpsRecordsByImei __cb);

    public boolean end_getGpsRecordsByImei(GpsGetExResponseHolder res, Ice.AsyncResult __result);

    public boolean getLatestGpsRecordByMapSn(LatestGpsGetRequest req, LatestGpsGetResponseHolder res);

    public boolean getLatestGpsRecordByMapSn(LatestGpsGetRequest req, LatestGpsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestGpsRecordByMapSn(LatestGpsGetRequest req);

    public Ice.AsyncResult begin_getLatestGpsRecordByMapSn(LatestGpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestGpsRecordByMapSn(LatestGpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestGpsRecordByMapSn(LatestGpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestGpsRecordByMapSn(LatestGpsGetRequest req, Callback_DaoGpsService_getLatestGpsRecordByMapSn __cb);

    public Ice.AsyncResult begin_getLatestGpsRecordByMapSn(LatestGpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getLatestGpsRecordByMapSn __cb);

    public boolean end_getLatestGpsRecordByMapSn(LatestGpsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getGpsRecordsByMapSn(GpsGetExRequest req, GpsGetExResponseHolder res);

    public boolean getGpsRecordsByMapSn(GpsGetExRequest req, GpsGetExResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsRecordsByMapSn(GpsGetExRequest req);

    public Ice.AsyncResult begin_getGpsRecordsByMapSn(GpsGetExRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsRecordsByMapSn(GpsGetExRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsRecordsByMapSn(GpsGetExRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsRecordsByMapSn(GpsGetExRequest req, Callback_DaoGpsService_getGpsRecordsByMapSn __cb);

    public Ice.AsyncResult begin_getGpsRecordsByMapSn(GpsGetExRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getGpsRecordsByMapSn __cb);

    public boolean end_getGpsRecordsByMapSn(GpsGetExResponseHolder res, Ice.AsyncResult __result);

    public boolean getSnMapRecords(Sn2DdMapGetReq req, Sn2DdMapGetResponseHolder res);

    public boolean getSnMapRecords(Sn2DdMapGetReq req, Sn2DdMapGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSnMapRecords(Sn2DdMapGetReq req);

    public Ice.AsyncResult begin_getSnMapRecords(Sn2DdMapGetReq req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSnMapRecords(Sn2DdMapGetReq req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getSnMapRecords(Sn2DdMapGetReq req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getSnMapRecords(Sn2DdMapGetReq req, Callback_DaoGpsService_getSnMapRecords __cb);

    public Ice.AsyncResult begin_getSnMapRecords(Sn2DdMapGetReq req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getSnMapRecords __cb);

    public boolean end_getSnMapRecords(Sn2DdMapGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getLatestRgpsRecord(LatestRgpsGetRequest req, LatestRgpsGetResponseHolder res);

    public boolean getLatestRgpsRecord(LatestRgpsGetRequest req, LatestRgpsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestRgpsRecord(LatestRgpsGetRequest req);

    public Ice.AsyncResult begin_getLatestRgpsRecord(LatestRgpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestRgpsRecord(LatestRgpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestRgpsRecord(LatestRgpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestRgpsRecord(LatestRgpsGetRequest req, Callback_DaoGpsService_getLatestRgpsRecord __cb);

    public Ice.AsyncResult begin_getLatestRgpsRecord(LatestRgpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getLatestRgpsRecord __cb);

    public boolean end_getLatestRgpsRecord(LatestRgpsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getLatestLocationByLbsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res);

    public boolean getLatestLocationByLbsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestLocationByLbsRecord(LatestGpsGetRequest req);

    public Ice.AsyncResult begin_getLatestLocationByLbsRecord(LatestGpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestLocationByLbsRecord(LatestGpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestLocationByLbsRecord(LatestGpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestLocationByLbsRecord(LatestGpsGetRequest req, Callback_DaoGpsService_getLatestLocationByLbsRecord __cb);

    public Ice.AsyncResult begin_getLatestLocationByLbsRecord(LatestGpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getLatestLocationByLbsRecord __cb);

    public boolean end_getLatestLocationByLbsRecord(LatestGpsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getDayLastGpsRecord(DayLastGpsGetRequest req, DayLastGpsGetResponseHolder res);

    public boolean getDayLastGpsRecord(DayLastGpsGetRequest req, DayLastGpsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDayLastGpsRecord(DayLastGpsGetRequest req);

    public Ice.AsyncResult begin_getDayLastGpsRecord(DayLastGpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDayLastGpsRecord(DayLastGpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDayLastGpsRecord(DayLastGpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDayLastGpsRecord(DayLastGpsGetRequest req, Callback_DaoGpsService_getDayLastGpsRecord __cb);

    public Ice.AsyncResult begin_getDayLastGpsRecord(DayLastGpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getDayLastGpsRecord __cb);

    public boolean end_getDayLastGpsRecord(DayLastGpsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getGpsBsRecords(GpsGetRequest req, GpsBsGetResponseHolder res);

    public boolean getGpsBsRecords(GpsGetRequest req, GpsBsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsBsRecords(GpsGetRequest req);

    public Ice.AsyncResult begin_getGpsBsRecords(GpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsBsRecords(GpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsBsRecords(GpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsBsRecords(GpsGetRequest req, Callback_DaoGpsService_getGpsBsRecords __cb);

    public Ice.AsyncResult begin_getGpsBsRecords(GpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getGpsBsRecords __cb);

    public boolean end_getGpsBsRecords(GpsBsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getFirstGpsBsRecord(GpsGetRequest req, GpsBsGetResponseHolder res);

    public boolean getFirstGpsBsRecord(GpsGetRequest req, GpsBsGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFirstGpsBsRecord(GpsGetRequest req);

    public Ice.AsyncResult begin_getFirstGpsBsRecord(GpsGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFirstGpsBsRecord(GpsGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFirstGpsBsRecord(GpsGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFirstGpsBsRecord(GpsGetRequest req, Callback_DaoGpsService_getFirstGpsBsRecord __cb);

    public Ice.AsyncResult begin_getFirstGpsBsRecord(GpsGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getFirstGpsBsRecord __cb);

    public boolean end_getFirstGpsBsRecord(GpsBsGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getLatestVolRecord(LatestVoltageGetRequest req, LatestVoltageGetResponseHolder res);

    public boolean getLatestVolRecord(LatestVoltageGetRequest req, LatestVoltageGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestVolRecord(LatestVoltageGetRequest req);

    public Ice.AsyncResult begin_getLatestVolRecord(LatestVoltageGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestVolRecord(LatestVoltageGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestVolRecord(LatestVoltageGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestVolRecord(LatestVoltageGetRequest req, Callback_DaoGpsService_getLatestVolRecord __cb);

    public Ice.AsyncResult begin_getLatestVolRecord(LatestVoltageGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getLatestVolRecord __cb);

    public boolean end_getLatestVolRecord(LatestVoltageGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getMaxVolDiff(DiffVoltageGetRequest req, DiffVoltageGetResponseHolder res);

    public boolean getMaxVolDiff(DiffVoltageGetRequest req, DiffVoltageGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMaxVolDiff(DiffVoltageGetRequest req);

    public Ice.AsyncResult begin_getMaxVolDiff(DiffVoltageGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMaxVolDiff(DiffVoltageGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMaxVolDiff(DiffVoltageGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMaxVolDiff(DiffVoltageGetRequest req, Callback_DaoGpsService_getMaxVolDiff __cb);

    public Ice.AsyncResult begin_getMaxVolDiff(DiffVoltageGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getMaxVolDiff __cb);

    public boolean end_getMaxVolDiff(DiffVoltageGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getVoltageRecords(VoltageGetRequest req, VoltageGetResponseHolder res);

    public boolean getVoltageRecords(VoltageGetRequest req, VoltageGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getVoltageRecords(VoltageGetRequest req);

    public Ice.AsyncResult begin_getVoltageRecords(VoltageGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getVoltageRecords(VoltageGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getVoltageRecords(VoltageGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getVoltageRecords(VoltageGetRequest req, Callback_DaoGpsService_getVoltageRecords __cb);

    public Ice.AsyncResult begin_getVoltageRecords(VoltageGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getVoltageRecords __cb);

    public boolean end_getVoltageRecords(VoltageGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getLatestBatteryRecord(LatestBatteryGetRequest req, LatestBatteryGetResponseHolder res);

    public boolean getLatestBatteryRecord(LatestBatteryGetRequest req, LatestBatteryGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestBatteryRecord(LatestBatteryGetRequest req);

    public Ice.AsyncResult begin_getLatestBatteryRecord(LatestBatteryGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatestBatteryRecord(LatestBatteryGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestBatteryRecord(LatestBatteryGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatestBatteryRecord(LatestBatteryGetRequest req, Callback_DaoGpsService_getLatestBatteryRecord __cb);

    public Ice.AsyncResult begin_getLatestBatteryRecord(LatestBatteryGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getLatestBatteryRecord __cb);

    public boolean end_getLatestBatteryRecord(LatestBatteryGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getDataCardInfo(DataCardGetRequest req, DataCardGetResponseHolder res);

    public boolean getDataCardInfo(DataCardGetRequest req, DataCardGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDataCardInfo(DataCardGetRequest req);

    public Ice.AsyncResult begin_getDataCardInfo(DataCardGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDataCardInfo(DataCardGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDataCardInfo(DataCardGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDataCardInfo(DataCardGetRequest req, Callback_DaoGpsService_getDataCardInfo __cb);

    public Ice.AsyncResult begin_getDataCardInfo(DataCardGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getDataCardInfo __cb);

    public boolean end_getDataCardInfo(DataCardGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getGpsWorkModeRecords(GpsWorkModeGetRequest req, GpsWorkModeGetResponseHolder res);

    public boolean getGpsWorkModeRecords(GpsWorkModeGetRequest req, GpsWorkModeGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsWorkModeRecords(GpsWorkModeGetRequest req);

    public Ice.AsyncResult begin_getGpsWorkModeRecords(GpsWorkModeGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getGpsWorkModeRecords(GpsWorkModeGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsWorkModeRecords(GpsWorkModeGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getGpsWorkModeRecords(GpsWorkModeGetRequest req, Callback_DaoGpsService_getGpsWorkModeRecords __cb);

    public Ice.AsyncResult begin_getGpsWorkModeRecords(GpsWorkModeGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getGpsWorkModeRecords __cb);

    public boolean end_getGpsWorkModeRecords(GpsWorkModeGetResponseHolder res, Ice.AsyncResult __result);

    public boolean getBsWorkModeRecords(BsWorkModeGetRequest req, BsWorkModeGetResponseHolder res);

    public boolean getBsWorkModeRecords(BsWorkModeGetRequest req, BsWorkModeGetResponseHolder res, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBsWorkModeRecords(BsWorkModeGetRequest req);

    public Ice.AsyncResult begin_getBsWorkModeRecords(BsWorkModeGetRequest req, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBsWorkModeRecords(BsWorkModeGetRequest req, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBsWorkModeRecords(BsWorkModeGetRequest req, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBsWorkModeRecords(BsWorkModeGetRequest req, Callback_DaoGpsService_getBsWorkModeRecords __cb);

    public Ice.AsyncResult begin_getBsWorkModeRecords(BsWorkModeGetRequest req, java.util.Map<String, String> __ctx, Callback_DaoGpsService_getBsWorkModeRecords __cb);

    public boolean end_getBsWorkModeRecords(BsWorkModeGetResponseHolder res, Ice.AsyncResult __result);
}
