// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

/**
 * Latest Rgps(GPS or rough GPS) record
 **/
public class LatestRgpsGetRequest implements java.lang.Cloneable, java.io.Serializable
{
    public long userID;

    public int apType;

    public int extraMapReq;

    public LatestRgpsGetRequest()
    {
    }

    public LatestRgpsGetRequest(long userID, int apType, int extraMapReq)
    {
        this.userID = userID;
        this.apType = apType;
        this.extraMapReq = extraMapReq;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LatestRgpsGetRequest _r = null;
        if(rhs instanceof LatestRgpsGetRequest)
        {
            _r = (LatestRgpsGetRequest)rhs;
        }

        if(_r != null)
        {
            if(userID != _r.userID)
            {
                return false;
            }
            if(apType != _r.apType)
            {
                return false;
            }
            if(extraMapReq != _r.extraMapReq)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::LatestRgpsGetRequest");
        __h = IceInternal.HashUtil.hashAdd(__h, userID);
        __h = IceInternal.HashUtil.hashAdd(__h, apType);
        __h = IceInternal.HashUtil.hashAdd(__h, extraMapReq);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(userID);
        __os.writeInt(apType);
        __os.writeInt(extraMapReq);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userID = __is.readLong();
        apType = __is.readInt();
        extraMapReq = __is.readInt();
    }

    public static final long serialVersionUID = 1337810197L;
}
