// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public class DiffVoltageGetResponse implements java.lang.Cloneable, java.io.Serializable
{
    public int oprResult;

    public int maxVolDiff;

    public DiffVoltageGetResponse()
    {
    }

    public DiffVoltageGetResponse(int oprResult, int maxVolDiff)
    {
        this.oprResult = oprResult;
        this.maxVolDiff = maxVolDiff;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DiffVoltageGetResponse _r = null;
        if(rhs instanceof DiffVoltageGetResponse)
        {
            _r = (DiffVoltageGetResponse)rhs;
        }

        if(_r != null)
        {
            if(oprResult != _r.oprResult)
            {
                return false;
            }
            if(maxVolDiff != _r.maxVolDiff)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::DiffVoltageGetResponse");
        __h = IceInternal.HashUtil.hashAdd(__h, oprResult);
        __h = IceInternal.HashUtil.hashAdd(__h, maxVolDiff);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(oprResult);
        __os.writeInt(maxVolDiff);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        oprResult = __is.readInt();
        maxVolDiff = __is.readInt();
    }

    public static final long serialVersionUID = 1250784511L;
}
