// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public interface _DaoGpsServiceDel extends Ice._ObjectDel
{
    boolean getBsRecords(BsGetRequest req, BsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getLatestBsRecord(LatestBsGetRequest req, LatestBsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getRecentBsRecords(RecentBsGetRequest req, RecentBsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getFirstBsRecord(BsGetRequest req, BsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getFirstGpsRecord(GpsGetRequest req, GpsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getLatestGpsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getRecentGpsRecords(RecentGpsGetRequest req, RecentGpsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getGpsRecords(GpsGetRequest req, GpsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getGpsRecordsEx(GpsGetRequest req, GpsGetExResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, LatestGpsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getGpsRecordsByImei(GpsGetRequest req, GpsGetExResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getLatestGpsRecordByMapSn(LatestGpsGetRequest req, LatestGpsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getGpsRecordsByMapSn(GpsGetExRequest req, GpsGetExResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getSnMapRecords(Sn2DdMapGetReq req, Sn2DdMapGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getLatestRgpsRecord(LatestRgpsGetRequest req, LatestRgpsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getLatestLocationByLbsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getDayLastGpsRecord(DayLastGpsGetRequest req, DayLastGpsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getGpsBsRecords(GpsGetRequest req, GpsBsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getFirstGpsBsRecord(GpsGetRequest req, GpsBsGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getLatestVolRecord(LatestVoltageGetRequest req, LatestVoltageGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getMaxVolDiff(DiffVoltageGetRequest req, DiffVoltageGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getVoltageRecords(VoltageGetRequest req, VoltageGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getLatestBatteryRecord(LatestBatteryGetRequest req, LatestBatteryGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getDataCardInfo(DataCardGetRequest req, DataCardGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getGpsWorkModeRecords(GpsWorkModeGetRequest req, GpsWorkModeGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;

    boolean getBsWorkModeRecords(BsWorkModeGetRequest req, BsWorkModeGetResponseHolder res, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
        throws IceInternal.LocalExceptionWrapper;
}
