// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public interface _DaoGpsServiceOperationsNC
{
    boolean getBsRecords(BsGetRequest req, BsGetResponseHolder res);

    boolean getLatestBsRecord(LatestBsGetRequest req, LatestBsGetResponseHolder res);

    boolean getRecentBsRecords(RecentBsGetRequest req, RecentBsGetResponseHolder res);

    boolean getFirstBsRecord(BsGetRequest req, BsGetResponseHolder res);

    boolean getFirstGpsRecord(GpsGetRequest req, GpsGetResponseHolder res);

    boolean getLatestGpsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res);

    boolean getRecentGpsRecords(RecentGpsGetRequest req, RecentGpsGetResponseHolder res);

    boolean getGpsRecords(GpsGetRequest req, GpsGetResponseHolder res);

    boolean getGpsRecordsEx(GpsGetRequest req, GpsGetExResponseHolder res);

    boolean getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, LatestGpsGetResponseHolder res);

    boolean getGpsRecordsByImei(GpsGetRequest req, GpsGetExResponseHolder res);

    boolean getLatestGpsRecordByMapSn(LatestGpsGetRequest req, LatestGpsGetResponseHolder res);

    boolean getGpsRecordsByMapSn(GpsGetExRequest req, GpsGetExResponseHolder res);

    boolean getSnMapRecords(Sn2DdMapGetReq req, Sn2DdMapGetResponseHolder res);

    boolean getLatestRgpsRecord(LatestRgpsGetRequest req, LatestRgpsGetResponseHolder res);

    boolean getLatestLocationByLbsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res);

    boolean getDayLastGpsRecord(DayLastGpsGetRequest req, DayLastGpsGetResponseHolder res);

    boolean getGpsBsRecords(GpsGetRequest req, GpsBsGetResponseHolder res);

    boolean getFirstGpsBsRecord(GpsGetRequest req, GpsBsGetResponseHolder res);

    boolean getLatestVolRecord(LatestVoltageGetRequest req, LatestVoltageGetResponseHolder res);

    boolean getMaxVolDiff(DiffVoltageGetRequest req, DiffVoltageGetResponseHolder res);

    boolean getVoltageRecords(VoltageGetRequest req, VoltageGetResponseHolder res);

    boolean getLatestBatteryRecord(LatestBatteryGetRequest req, LatestBatteryGetResponseHolder res);

    boolean getDataCardInfo(DataCardGetRequest req, DataCardGetResponseHolder res);

    boolean getGpsWorkModeRecords(GpsWorkModeGetRequest req, GpsWorkModeGetResponseHolder res);

    boolean getBsWorkModeRecords(BsWorkModeGetRequest req, BsWorkModeGetResponseHolder res);
}
