// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public abstract class _DaoGpsServiceDisp extends Ice.ObjectImpl implements DaoGpsService
{
    protected void
    ice_copyStateFrom(Ice.Object __obj)
        throws java.lang.CloneNotSupportedException
    {
        throw new java.lang.CloneNotSupportedException();
    }

    public static final String[] __ids =
    {
        "::HDaoGps::DaoGpsService",
        "::Ice::Object"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[0];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[0];
    }

    public static String ice_staticId()
    {
        return __ids[0];
    }

    public final boolean getBsRecords(BsGetRequest req, BsGetResponseHolder res)
    {
        return getBsRecords(req, res, null);
    }

    public final boolean getBsWorkModeRecords(BsWorkModeGetRequest req, BsWorkModeGetResponseHolder res)
    {
        return getBsWorkModeRecords(req, res, null);
    }

    public final boolean getDataCardInfo(DataCardGetRequest req, DataCardGetResponseHolder res)
    {
        return getDataCardInfo(req, res, null);
    }

    public final boolean getDayLastGpsRecord(DayLastGpsGetRequest req, DayLastGpsGetResponseHolder res)
    {
        return getDayLastGpsRecord(req, res, null);
    }

    public final boolean getFirstBsRecord(BsGetRequest req, BsGetResponseHolder res)
    {
        return getFirstBsRecord(req, res, null);
    }

    public final boolean getFirstGpsBsRecord(GpsGetRequest req, GpsBsGetResponseHolder res)
    {
        return getFirstGpsBsRecord(req, res, null);
    }

    public final boolean getFirstGpsRecord(GpsGetRequest req, GpsGetResponseHolder res)
    {
        return getFirstGpsRecord(req, res, null);
    }

    public final boolean getGpsBsRecords(GpsGetRequest req, GpsBsGetResponseHolder res)
    {
        return getGpsBsRecords(req, res, null);
    }

    public final boolean getGpsRecords(GpsGetRequest req, GpsGetResponseHolder res)
    {
        return getGpsRecords(req, res, null);
    }

    public final boolean getGpsRecordsByImei(GpsGetRequest req, GpsGetExResponseHolder res)
    {
        return getGpsRecordsByImei(req, res, null);
    }

    public final boolean getGpsRecordsByMapSn(GpsGetExRequest req, GpsGetExResponseHolder res)
    {
        return getGpsRecordsByMapSn(req, res, null);
    }

    public final boolean getGpsRecordsEx(GpsGetRequest req, GpsGetExResponseHolder res)
    {
        return getGpsRecordsEx(req, res, null);
    }

    public final boolean getGpsWorkModeRecords(GpsWorkModeGetRequest req, GpsWorkModeGetResponseHolder res)
    {
        return getGpsWorkModeRecords(req, res, null);
    }

    public final boolean getLatestBatteryRecord(LatestBatteryGetRequest req, LatestBatteryGetResponseHolder res)
    {
        return getLatestBatteryRecord(req, res, null);
    }

    public final boolean getLatestBsRecord(LatestBsGetRequest req, LatestBsGetResponseHolder res)
    {
        return getLatestBsRecord(req, res, null);
    }

    public final boolean getLatestGpsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res)
    {
        return getLatestGpsRecord(req, res, null);
    }

    public final boolean getLatestGpsRecordByImei(LatestGpsGetRequestWithBindTime req, LatestGpsGetResponseHolder res)
    {
        return getLatestGpsRecordByImei(req, res, null);
    }

    public final boolean getLatestGpsRecordByMapSn(LatestGpsGetRequest req, LatestGpsGetResponseHolder res)
    {
        return getLatestGpsRecordByMapSn(req, res, null);
    }

    public final boolean getLatestLocationByLbsRecord(LatestGpsGetRequest req, LatestGpsGetResponseHolder res)
    {
        return getLatestLocationByLbsRecord(req, res, null);
    }

    public final boolean getLatestRgpsRecord(LatestRgpsGetRequest req, LatestRgpsGetResponseHolder res)
    {
        return getLatestRgpsRecord(req, res, null);
    }

    public final boolean getLatestVolRecord(LatestVoltageGetRequest req, LatestVoltageGetResponseHolder res)
    {
        return getLatestVolRecord(req, res, null);
    }

    public final boolean getMaxVolDiff(DiffVoltageGetRequest req, DiffVoltageGetResponseHolder res)
    {
        return getMaxVolDiff(req, res, null);
    }

    public final boolean getRecentBsRecords(RecentBsGetRequest req, RecentBsGetResponseHolder res)
    {
        return getRecentBsRecords(req, res, null);
    }

    public final boolean getRecentGpsRecords(RecentGpsGetRequest req, RecentGpsGetResponseHolder res)
    {
        return getRecentGpsRecords(req, res, null);
    }

    public final boolean getSnMapRecords(Sn2DdMapGetReq req, Sn2DdMapGetResponseHolder res)
    {
        return getSnMapRecords(req, res, null);
    }

    public final boolean getVoltageRecords(VoltageGetRequest req, VoltageGetResponseHolder res)
    {
        return getVoltageRecords(req, res, null);
    }

    public static Ice.DispatchStatus ___getBsRecords(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        BsGetRequest req;
        req = new BsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        BsGetResponseHolder res = new BsGetResponseHolder();
        boolean __ret = __obj.getBsRecords(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getLatestBsRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        LatestBsGetRequest req;
        req = new LatestBsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        LatestBsGetResponseHolder res = new LatestBsGetResponseHolder();
        boolean __ret = __obj.getLatestBsRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getRecentBsRecords(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        RecentBsGetRequest req;
        req = new RecentBsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        RecentBsGetResponseHolder res = new RecentBsGetResponseHolder();
        boolean __ret = __obj.getRecentBsRecords(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getFirstBsRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        BsGetRequest req;
        req = new BsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        BsGetResponseHolder res = new BsGetResponseHolder();
        boolean __ret = __obj.getFirstBsRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getFirstGpsRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        GpsGetRequest req;
        req = new GpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        GpsGetResponseHolder res = new GpsGetResponseHolder();
        boolean __ret = __obj.getFirstGpsRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getLatestGpsRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        LatestGpsGetRequest req;
        req = new LatestGpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        LatestGpsGetResponseHolder res = new LatestGpsGetResponseHolder();
        boolean __ret = __obj.getLatestGpsRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getRecentGpsRecords(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        RecentGpsGetRequest req;
        req = new RecentGpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        RecentGpsGetResponseHolder res = new RecentGpsGetResponseHolder();
        boolean __ret = __obj.getRecentGpsRecords(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getGpsRecords(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        GpsGetRequest req;
        req = new GpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        GpsGetResponseHolder res = new GpsGetResponseHolder();
        boolean __ret = __obj.getGpsRecords(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getGpsRecordsEx(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        GpsGetRequest req;
        req = new GpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        GpsGetExResponseHolder res = new GpsGetExResponseHolder();
        boolean __ret = __obj.getGpsRecordsEx(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getLatestGpsRecordByImei(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        LatestGpsGetRequestWithBindTime req;
        req = new LatestGpsGetRequestWithBindTime();
        req.__read(__is);
        __inS.endReadParams();
        LatestGpsGetResponseHolder res = new LatestGpsGetResponseHolder();
        boolean __ret = __obj.getLatestGpsRecordByImei(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getGpsRecordsByImei(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        GpsGetRequest req;
        req = new GpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        GpsGetExResponseHolder res = new GpsGetExResponseHolder();
        boolean __ret = __obj.getGpsRecordsByImei(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getLatestGpsRecordByMapSn(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        LatestGpsGetRequest req;
        req = new LatestGpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        LatestGpsGetResponseHolder res = new LatestGpsGetResponseHolder();
        boolean __ret = __obj.getLatestGpsRecordByMapSn(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getGpsRecordsByMapSn(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        GpsGetExRequest req;
        req = new GpsGetExRequest();
        req.__read(__is);
        __inS.endReadParams();
        GpsGetExResponseHolder res = new GpsGetExResponseHolder();
        boolean __ret = __obj.getGpsRecordsByMapSn(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getSnMapRecords(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        Sn2DdMapGetReq req;
        req = new Sn2DdMapGetReq();
        req.__read(__is);
        __inS.endReadParams();
        Sn2DdMapGetResponseHolder res = new Sn2DdMapGetResponseHolder();
        boolean __ret = __obj.getSnMapRecords(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getLatestRgpsRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        LatestRgpsGetRequest req;
        req = new LatestRgpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        LatestRgpsGetResponseHolder res = new LatestRgpsGetResponseHolder();
        boolean __ret = __obj.getLatestRgpsRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getLatestLocationByLbsRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        LatestGpsGetRequest req;
        req = new LatestGpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        LatestGpsGetResponseHolder res = new LatestGpsGetResponseHolder();
        boolean __ret = __obj.getLatestLocationByLbsRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getDayLastGpsRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        DayLastGpsGetRequest req;
        req = new DayLastGpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        DayLastGpsGetResponseHolder res = new DayLastGpsGetResponseHolder();
        boolean __ret = __obj.getDayLastGpsRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getGpsBsRecords(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        GpsGetRequest req;
        req = new GpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        GpsBsGetResponseHolder res = new GpsBsGetResponseHolder();
        boolean __ret = __obj.getGpsBsRecords(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getFirstGpsBsRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        GpsGetRequest req;
        req = new GpsGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        GpsBsGetResponseHolder res = new GpsBsGetResponseHolder();
        boolean __ret = __obj.getFirstGpsBsRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getLatestVolRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        LatestVoltageGetRequest req;
        req = new LatestVoltageGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        LatestVoltageGetResponseHolder res = new LatestVoltageGetResponseHolder();
        boolean __ret = __obj.getLatestVolRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getMaxVolDiff(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        DiffVoltageGetRequest req;
        req = new DiffVoltageGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        DiffVoltageGetResponseHolder res = new DiffVoltageGetResponseHolder();
        boolean __ret = __obj.getMaxVolDiff(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getVoltageRecords(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        VoltageGetRequest req;
        req = new VoltageGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        VoltageGetResponseHolder res = new VoltageGetResponseHolder();
        boolean __ret = __obj.getVoltageRecords(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getLatestBatteryRecord(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        LatestBatteryGetRequest req;
        req = new LatestBatteryGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        LatestBatteryGetResponseHolder res = new LatestBatteryGetResponseHolder();
        boolean __ret = __obj.getLatestBatteryRecord(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getDataCardInfo(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        DataCardGetRequest req;
        req = new DataCardGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        DataCardGetResponseHolder res = new DataCardGetResponseHolder();
        boolean __ret = __obj.getDataCardInfo(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getGpsWorkModeRecords(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        GpsWorkModeGetRequest req;
        req = new GpsWorkModeGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        GpsWorkModeGetResponseHolder res = new GpsWorkModeGetResponseHolder();
        boolean __ret = __obj.getGpsWorkModeRecords(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getBsWorkModeRecords(DaoGpsService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        BsWorkModeGetRequest req;
        req = new BsWorkModeGetRequest();
        req.__read(__is);
        __inS.endReadParams();
        BsWorkModeGetResponseHolder res = new BsWorkModeGetResponseHolder();
        boolean __ret = __obj.getBsWorkModeRecords(req, res, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        res.value.__write(__os);
        __os.writeBool(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    private final static String[] __all =
    {
        "getBsRecords",
        "getBsWorkModeRecords",
        "getDataCardInfo",
        "getDayLastGpsRecord",
        "getFirstBsRecord",
        "getFirstGpsBsRecord",
        "getFirstGpsRecord",
        "getGpsBsRecords",
        "getGpsRecords",
        "getGpsRecordsByImei",
        "getGpsRecordsByMapSn",
        "getGpsRecordsEx",
        "getGpsWorkModeRecords",
        "getLatestBatteryRecord",
        "getLatestBsRecord",
        "getLatestGpsRecord",
        "getLatestGpsRecordByImei",
        "getLatestGpsRecordByMapSn",
        "getLatestLocationByLbsRecord",
        "getLatestRgpsRecord",
        "getLatestVolRecord",
        "getMaxVolDiff",
        "getRecentBsRecords",
        "getRecentGpsRecords",
        "getSnMapRecords",
        "getVoltageRecords",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    public Ice.DispatchStatus __dispatch(IceInternal.Incoming in, Ice.Current __current)
    {
        int pos = java.util.Arrays.binarySearch(__all, __current.operation);
        if(pos < 0)
        {
            throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return ___getBsRecords(this, in, __current);
            }
            case 1:
            {
                return ___getBsWorkModeRecords(this, in, __current);
            }
            case 2:
            {
                return ___getDataCardInfo(this, in, __current);
            }
            case 3:
            {
                return ___getDayLastGpsRecord(this, in, __current);
            }
            case 4:
            {
                return ___getFirstBsRecord(this, in, __current);
            }
            case 5:
            {
                return ___getFirstGpsBsRecord(this, in, __current);
            }
            case 6:
            {
                return ___getFirstGpsRecord(this, in, __current);
            }
            case 7:
            {
                return ___getGpsBsRecords(this, in, __current);
            }
            case 8:
            {
                return ___getGpsRecords(this, in, __current);
            }
            case 9:
            {
                return ___getGpsRecordsByImei(this, in, __current);
            }
            case 10:
            {
                return ___getGpsRecordsByMapSn(this, in, __current);
            }
            case 11:
            {
                return ___getGpsRecordsEx(this, in, __current);
            }
            case 12:
            {
                return ___getGpsWorkModeRecords(this, in, __current);
            }
            case 13:
            {
                return ___getLatestBatteryRecord(this, in, __current);
            }
            case 14:
            {
                return ___getLatestBsRecord(this, in, __current);
            }
            case 15:
            {
                return ___getLatestGpsRecord(this, in, __current);
            }
            case 16:
            {
                return ___getLatestGpsRecordByImei(this, in, __current);
            }
            case 17:
            {
                return ___getLatestGpsRecordByMapSn(this, in, __current);
            }
            case 18:
            {
                return ___getLatestLocationByLbsRecord(this, in, __current);
            }
            case 19:
            {
                return ___getLatestRgpsRecord(this, in, __current);
            }
            case 20:
            {
                return ___getLatestVolRecord(this, in, __current);
            }
            case 21:
            {
                return ___getMaxVolDiff(this, in, __current);
            }
            case 22:
            {
                return ___getRecentBsRecords(this, in, __current);
            }
            case 23:
            {
                return ___getRecentGpsRecords(this, in, __current);
            }
            case 24:
            {
                return ___getSnMapRecords(this, in, __current);
            }
            case 25:
            {
                return ___getVoltageRecords(this, in, __current);
            }
            case 26:
            {
                return ___ice_id(this, in, __current);
            }
            case 27:
            {
                return ___ice_ids(this, in, __current);
            }
            case 28:
            {
                return ___ice_isA(this, in, __current);
            }
            case 29:
            {
                return ___ice_ping(this, in, __current);
            }
        }

        assert(false);
        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = 0L;
}
