// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

/**
 * Recent BaseStation records
 **/
public class RecentBsGetRequest implements java.lang.Cloneable, java.io.Serializable
{
    public long userID;

    public int apType;

    public int apSubType;

    public int reqCount;

    public RecentBsGetRequest()
    {
    }

    public RecentBsGetRequest(long userID, int apType, int apSubType, int reqCount)
    {
        this.userID = userID;
        this.apType = apType;
        this.apSubType = apSubType;
        this.reqCount = reqCount;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RecentBsGetRequest _r = null;
        if(rhs instanceof RecentBsGetRequest)
        {
            _r = (RecentBsGetRequest)rhs;
        }

        if(_r != null)
        {
            if(userID != _r.userID)
            {
                return false;
            }
            if(apType != _r.apType)
            {
                return false;
            }
            if(apSubType != _r.apSubType)
            {
                return false;
            }
            if(reqCount != _r.reqCount)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::RecentBsGetRequest");
        __h = IceInternal.HashUtil.hashAdd(__h, userID);
        __h = IceInternal.HashUtil.hashAdd(__h, apType);
        __h = IceInternal.HashUtil.hashAdd(__h, apSubType);
        __h = IceInternal.HashUtil.hashAdd(__h, reqCount);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(userID);
        __os.writeInt(apType);
        __os.writeInt(apSubType);
        __os.writeInt(reqCount);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userID = __is.readLong();
        apType = __is.readInt();
        apSubType = __is.readInt();
        reqCount = __is.readInt();
    }

    public static final long serialVersionUID = -176403571L;
}
