// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

/**
 * Last Gps record for the request date
 **/
public class DayLastGpsGetRequest implements java.lang.Cloneable, java.io.Serializable
{
    public long userID;

    public int apType;

    public int extraMapReq;

    public int year;

    public int month;

    public int day;

    public DayLastGpsGetRequest()
    {
    }

    public DayLastGpsGetRequest(long userID, int apType, int extraMapReq, int year, int month, int day)
    {
        this.userID = userID;
        this.apType = apType;
        this.extraMapReq = extraMapReq;
        this.year = year;
        this.month = month;
        this.day = day;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DayLastGpsGetRequest _r = null;
        if(rhs instanceof DayLastGpsGetRequest)
        {
            _r = (DayLastGpsGetRequest)rhs;
        }

        if(_r != null)
        {
            if(userID != _r.userID)
            {
                return false;
            }
            if(apType != _r.apType)
            {
                return false;
            }
            if(extraMapReq != _r.extraMapReq)
            {
                return false;
            }
            if(year != _r.year)
            {
                return false;
            }
            if(month != _r.month)
            {
                return false;
            }
            if(day != _r.day)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::DayLastGpsGetRequest");
        __h = IceInternal.HashUtil.hashAdd(__h, userID);
        __h = IceInternal.HashUtil.hashAdd(__h, apType);
        __h = IceInternal.HashUtil.hashAdd(__h, extraMapReq);
        __h = IceInternal.HashUtil.hashAdd(__h, year);
        __h = IceInternal.HashUtil.hashAdd(__h, month);
        __h = IceInternal.HashUtil.hashAdd(__h, day);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(userID);
        __os.writeInt(apType);
        __os.writeInt(extraMapReq);
        __os.writeInt(year);
        __os.writeInt(month);
        __os.writeInt(day);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userID = __is.readLong();
        apType = __is.readInt();
        extraMapReq = __is.readInt();
        year = __is.readInt();
        month = __is.readInt();
        day = __is.readInt();
    }

    public static final long serialVersionUID = 1282099086L;
}
