// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public class BsRecord implements java.lang.Cloneable, java.io.Serializable
{
    public int gpsTime;

    public int storeTime;

    public int mcc;

    public int mnc;

    public BsInfo[] bsInfos;

    public BsRecord()
    {
    }

    public BsRecord(int gpsTime, int storeTime, int mcc, int mnc, BsInfo[] bsInfos)
    {
        this.gpsTime = gpsTime;
        this.storeTime = storeTime;
        this.mcc = mcc;
        this.mnc = mnc;
        this.bsInfos = bsInfos;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        BsRecord _r = null;
        if(rhs instanceof BsRecord)
        {
            _r = (BsRecord)rhs;
        }

        if(_r != null)
        {
            if(gpsTime != _r.gpsTime)
            {
                return false;
            }
            if(storeTime != _r.storeTime)
            {
                return false;
            }
            if(mcc != _r.mcc)
            {
                return false;
            }
            if(mnc != _r.mnc)
            {
                return false;
            }
            if(!java.util.Arrays.equals(bsInfos, _r.bsInfos))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::BsRecord");
        __h = IceInternal.HashUtil.hashAdd(__h, gpsTime);
        __h = IceInternal.HashUtil.hashAdd(__h, storeTime);
        __h = IceInternal.HashUtil.hashAdd(__h, mcc);
        __h = IceInternal.HashUtil.hashAdd(__h, mnc);
        __h = IceInternal.HashUtil.hashAdd(__h, bsInfos);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(gpsTime);
        __os.writeInt(storeTime);
        __os.writeInt(mcc);
        __os.writeInt(mnc);
        BsInfoArrayHelper.write(__os, bsInfos);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        gpsTime = __is.readInt();
        storeTime = __is.readInt();
        mcc = __is.readInt();
        mnc = __is.readInt();
        bsInfos = BsInfoArrayHelper.read(__is);
    }

    public static final long serialVersionUID = -842860500L;
}
