// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public final class BsWorkModeRecordsHelper
{
    public static void
    write(IceInternal.BasicStream __os, BsWorkModeRecord[] __v)
    {
        if(__v == null)
        {
            __os.writeSize(0);
        }
        else
        {
            __os.writeSize(__v.length);
            for(int __i0 = 0; __i0 < __v.length; __i0++)
            {
                __v[__i0].__write(__os);
            }
        }
    }

    public static BsWorkModeRecord[]
    read(IceInternal.BasicStream __is)
    {
        BsWorkModeRecord[] __v;
        final int __len0 = __is.readAndCheckSeqSize(25);
        __v = new BsWorkModeRecord[__len0];
        for(int __i0 = 0; __i0 < __len0; __i0++)
        {
            __v[__i0] = new BsWorkModeRecord();
            __v[__i0].__read(__is);
        }
        return __v;
    }
}
