// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public class DataCardGetResponse implements java.lang.Cloneable, java.io.Serializable
{
    public int oprResult;

    public DataCardInfo cardInfo;

    public DataCardGetResponse()
    {
    }

    public DataCardGetResponse(int oprResult, DataCardInfo cardInfo)
    {
        this.oprResult = oprResult;
        this.cardInfo = cardInfo;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DataCardGetResponse _r = null;
        if(rhs instanceof DataCardGetResponse)
        {
            _r = (DataCardGetResponse)rhs;
        }

        if(_r != null)
        {
            if(oprResult != _r.oprResult)
            {
                return false;
            }
            if(cardInfo != _r.cardInfo)
            {
                if(cardInfo == null || _r.cardInfo == null || !cardInfo.equals(_r.cardInfo))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::DataCardGetResponse");
        __h = IceInternal.HashUtil.hashAdd(__h, oprResult);
        __h = IceInternal.HashUtil.hashAdd(__h, cardInfo);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(oprResult);
        cardInfo.__write(__os);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        oprResult = __is.readInt();
        cardInfo = new DataCardInfo();
        cardInfo.__read(__is);
    }

    public static final long serialVersionUID = -193807582L;
}
