// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

/**
 * Voltage max diff
 **/
public class DiffVoltageGetRequest implements java.lang.Cloneable, java.io.Serializable
{
    public long userID;

    public int apType;

    public int startTime;

    public int endTime;

    public DiffVoltageGetRequest()
    {
    }

    public DiffVoltageGetRequest(long userID, int apType, int startTime, int endTime)
    {
        this.userID = userID;
        this.apType = apType;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DiffVoltageGetRequest _r = null;
        if(rhs instanceof DiffVoltageGetRequest)
        {
            _r = (DiffVoltageGetRequest)rhs;
        }

        if(_r != null)
        {
            if(userID != _r.userID)
            {
                return false;
            }
            if(apType != _r.apType)
            {
                return false;
            }
            if(startTime != _r.startTime)
            {
                return false;
            }
            if(endTime != _r.endTime)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::DiffVoltageGetRequest");
        __h = IceInternal.HashUtil.hashAdd(__h, userID);
        __h = IceInternal.HashUtil.hashAdd(__h, apType);
        __h = IceInternal.HashUtil.hashAdd(__h, startTime);
        __h = IceInternal.HashUtil.hashAdd(__h, endTime);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(userID);
        __os.writeInt(apType);
        __os.writeInt(startTime);
        __os.writeInt(endTime);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userID = __is.readLong();
        apType = __is.readInt();
        startTime = __is.readInt();
        endTime = __is.readInt();
    }

    public static final long serialVersionUID = 1430707391L;
}
