// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public class Sn2DdMapGetResponse implements java.lang.Cloneable, java.io.Serializable
{
    public int oprResult;

    public SnMapRecord curMapRecord;

    public SnMapRecord[] historyMapRecords;

    public Sn2DdMapGetResponse()
    {
    }

    public Sn2DdMapGetResponse(int oprResult, SnMapRecord curMapRecord, SnMapRecord[] historyMapRecords)
    {
        this.oprResult = oprResult;
        this.curMapRecord = curMapRecord;
        this.historyMapRecords = historyMapRecords;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Sn2DdMapGetResponse _r = null;
        if(rhs instanceof Sn2DdMapGetResponse)
        {
            _r = (Sn2DdMapGetResponse)rhs;
        }

        if(_r != null)
        {
            if(oprResult != _r.oprResult)
            {
                return false;
            }
            if(curMapRecord != _r.curMapRecord)
            {
                if(curMapRecord == null || _r.curMapRecord == null || !curMapRecord.equals(_r.curMapRecord))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(historyMapRecords, _r.historyMapRecords))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::Sn2DdMapGetResponse");
        __h = IceInternal.HashUtil.hashAdd(__h, oprResult);
        __h = IceInternal.HashUtil.hashAdd(__h, curMapRecord);
        __h = IceInternal.HashUtil.hashAdd(__h, historyMapRecords);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(oprResult);
        curMapRecord.__write(__os);
        SnMapRecordsHelper.write(__os, historyMapRecords);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        oprResult = __is.readInt();
        curMapRecord = new SnMapRecord();
        curMapRecord.__read(__is);
        historyMapRecords = SnMapRecordsHelper.read(__is);
    }

    public static final long serialVersionUID = 1256851261L;
}
