// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

public class VoltageGetResponse implements java.lang.Cloneable, java.io.Serializable
{
    public int oprResult;

    public VoltageRecord[] records;

    public boolean finishFlag;

    public int lastRecTime;

    public VoltageGetResponse()
    {
    }

    public VoltageGetResponse(int oprResult, VoltageRecord[] records, boolean finishFlag, int lastRecTime)
    {
        this.oprResult = oprResult;
        this.records = records;
        this.finishFlag = finishFlag;
        this.lastRecTime = lastRecTime;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        VoltageGetResponse _r = null;
        if(rhs instanceof VoltageGetResponse)
        {
            _r = (VoltageGetResponse)rhs;
        }

        if(_r != null)
        {
            if(oprResult != _r.oprResult)
            {
                return false;
            }
            if(!java.util.Arrays.equals(records, _r.records))
            {
                return false;
            }
            if(finishFlag != _r.finishFlag)
            {
                return false;
            }
            if(lastRecTime != _r.lastRecTime)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::VoltageGetResponse");
        __h = IceInternal.HashUtil.hashAdd(__h, oprResult);
        __h = IceInternal.HashUtil.hashAdd(__h, records);
        __h = IceInternal.HashUtil.hashAdd(__h, finishFlag);
        __h = IceInternal.HashUtil.hashAdd(__h, lastRecTime);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(oprResult);
        VoltageRecordsHelper.write(__os, records);
        __os.writeBool(finishFlag);
        __os.writeInt(lastRecTime);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        oprResult = __is.readInt();
        records = VoltageRecordsHelper.read(__is);
        finishFlag = __is.readBool();
        lastRecTime = __is.readInt();
    }

    public static final long serialVersionUID = 1429890772L;
}
