// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `HDao_gps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HDaoGps;

/**
 * workmode record: gsensor and workmode field
 **/
public class GpsWorkModeRecord implements java.lang.Cloneable, java.io.Serializable
{
    public int gpsTime;

    public int lng;

    public int lat;

    public int alt;

    public int speed;

    public int dir;

    public int gsensor;

    public int workmode;

    public int storeTime;

    public GpsWorkModeRecord()
    {
    }

    public GpsWorkModeRecord(int gpsTime, int lng, int lat, int alt, int speed, int dir, int gsensor, int workmode, int storeTime)
    {
        this.gpsTime = gpsTime;
        this.lng = lng;
        this.lat = lat;
        this.alt = alt;
        this.speed = speed;
        this.dir = dir;
        this.gsensor = gsensor;
        this.workmode = workmode;
        this.storeTime = storeTime;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        GpsWorkModeRecord _r = null;
        if(rhs instanceof GpsWorkModeRecord)
        {
            _r = (GpsWorkModeRecord)rhs;
        }

        if(_r != null)
        {
            if(gpsTime != _r.gpsTime)
            {
                return false;
            }
            if(lng != _r.lng)
            {
                return false;
            }
            if(lat != _r.lat)
            {
                return false;
            }
            if(alt != _r.alt)
            {
                return false;
            }
            if(speed != _r.speed)
            {
                return false;
            }
            if(dir != _r.dir)
            {
                return false;
            }
            if(gsensor != _r.gsensor)
            {
                return false;
            }
            if(workmode != _r.workmode)
            {
                return false;
            }
            if(storeTime != _r.storeTime)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::HDaoGps::GpsWorkModeRecord");
        __h = IceInternal.HashUtil.hashAdd(__h, gpsTime);
        __h = IceInternal.HashUtil.hashAdd(__h, lng);
        __h = IceInternal.HashUtil.hashAdd(__h, lat);
        __h = IceInternal.HashUtil.hashAdd(__h, alt);
        __h = IceInternal.HashUtil.hashAdd(__h, speed);
        __h = IceInternal.HashUtil.hashAdd(__h, dir);
        __h = IceInternal.HashUtil.hashAdd(__h, gsensor);
        __h = IceInternal.HashUtil.hashAdd(__h, workmode);
        __h = IceInternal.HashUtil.hashAdd(__h, storeTime);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(gpsTime);
        __os.writeInt(lng);
        __os.writeInt(lat);
        __os.writeInt(alt);
        __os.writeInt(speed);
        __os.writeInt(dir);
        __os.writeInt(gsensor);
        __os.writeInt(workmode);
        __os.writeInt(storeTime);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        gpsTime = __is.readInt();
        lng = __is.readInt();
        lat = __is.readInt();
        alt = __is.readInt();
        speed = __is.readInt();
        dir = __is.readInt();
        gsensor = __is.readInt();
        workmode = __is.readInt();
        storeTime = __is.readInt();
    }

    public static final long serialVersionUID = -237453292L;
}
